[package]
name = "API_1"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["json"] }
tokio = { version = "1.47", features=["full] }
serde_json = "1.0"
iced = { version = "0.13.1", features = ["tokio"] }
