[package]
name = "API_2"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = {version = "0.17.0"}
tokio = {version = "1.48.0", features=["full"]}
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
log = "0.4.28"
pretty_env_logger = "0.5.0"